services:
  truenas-backup-config:
    build: .
    container_name: truenas-backup-config
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./truenas-backup:/app/truenas-backup